{{- range .Values.components }}
{{- if .image.deployment.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .image.comp_name }}
  {{- if .image.namespace }}
  namespace: {{ .image.namespace }}
  {{- else }}
  namespace: default
  {{- end }}  
  labels:
    instance: {{ .image.comp_name }}
spec:
  {{- if .image.replicas }}
  replicas: {{ .image.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector: 
    matchLabels:
      instance: {{ .image.comp_name }}    
  template:
    metadata:
      labels:
        instance: {{ .image.comp_name }}   
    spec:
      containers:
        - name: {{ .image.comp_name }}
          image: {{ .image.image_name }}:{{ .image.tag }}
          imagePullPolicy: IfNotPresent
          {{- if .image.env }}
          env:
            {{- toYaml .image.env | nindent 12 }}
          {{- end }}                                                                              
          ports:
            - name: http
              containerPort: {{ .image.targetport }}
              protocol: TCP
          {{- if .image.resources }}
          resources:
            {{- toYaml .image.resources | nindent 12 }}
          {{- end }}
          {{- if .image.volumeMounts }}              
          volumeMounts:                    
            {{- toYaml .image.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .image.volumes }}
      volumes:                  
        {{- toYaml .image.volumes | nindent 6 }}
      {{- end }}
{{- end -}}
{{- end -}}                              